<?php

namespace App\Services\Video;

use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use RuntimeException;

class VideoProcessor
{
    protected string $ffmpeg;
    protected string $ffprobe;
    protected string $disk = 'local'; // storage/app/

    public function __construct()
    {
        $this->ffmpeg = config('files.ffmpeg_path', env('FFMPEG_PATH', '/usr/bin/ffmpeg'));
        $this->ffprobe = config('files.ffprobe_path', env('FFPROBE_PATH', '/usr/bin/ffprobe'));
    }

    /**
     * Convert an input file to multiple qualities and store them under
     * storage/app/private/lessons/{lessonId}/videos/{quality}p.mp4
     *
     * Returns array quality => relative_path
     *
     * @param string $absoluteInputPath absolute file path (full path)
     * @param array $qualities array of integers e.g. ['360','480','720']
     * @param int $lessonId
     * @return array
     * @throws RuntimeException
     */
    public function convertToQualities(string $absoluteInputPath, array $qualities, int $lessonId): array
    {
        $results = [];
        foreach ($qualities as $q) {
            $outRel = "private/lessons/{$lessonId}/videos/{$q}p.mp4";
            $outAbs = storage_path('app/' . $outRel);

            // ensure directory exists
            $dir = dirname($outAbs);
            if (!is_dir($dir)) {
                mkdir($dir, 0755, true);
            }

            // build ffmpeg cmd
            // Using -movflags +faststart helps streaming MP4
            $cmd = escapeshellcmd($this->ffmpeg)
                . ' -y -i ' . escapeshellarg($absoluteInputPath)
                . ' -vf ' . escapeshellarg("scale=-2:{$q}")
                . ' -c:v libx264 -preset slow -crf 23'
                . ' -c:a aac -b:a 128k'
                . ' -movflags +faststart '
                . ' ' . escapeshellarg($outAbs);

            exec($cmd . ' 2>&1', $output, $returnVar);

            if ($returnVar !== 0) {
                // log to laravel log
                \Log::error("ffmpeg failed for lesson {$lessonId} {$q}p", ['cmd'=>$cmd, 'output'=>$output]);
                continue;
            }

            // store relative path
            $results[$q] = $outRel;
        }

        if (empty($results)) {
            throw new RuntimeException("No outputs generated by ffmpeg for {$absoluteInputPath}");
        }

        return $results;
    }

    /**
     * Return duration in seconds using ffprobe
     *
     * @param string $absoluteInputPath
     * @return int|null
     */
    public function getDuration(string $absoluteInputPath): ?int
    {
        $cmd = escapeshellcmd($this->ffprobe)
            . " -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "
            . escapeshellarg($absoluteInputPath);

        exec($cmd . ' 2>&1', $output, $returnVar);

        if ($returnVar !== 0 || empty($output)) {
            \Log::warning("ffprobe failed for {$absoluteInputPath}", ['cmd'=>$cmd,'output'=>$output ?? null]);
            return null;
        }

        $duration = (float) ($output[0] ?? 0.0);
        return (int) ceil($duration);
    }
}
